# See https://wiki.hypr.land/Configuring/Monitors/

# monitor = name, resolution, position, scale

# monitorv2 {
#   name = string
#   resolution = WxH@rate (preferred, highres, highrr, maxwidth)
#   position = XxY (auto, auto-right/left/up/down, auto-center-right/left/up/down)
#   scale = number (auto)
#   transform =
      # 0 - normal (no transforms)
      # 1 - 90 degrees
      # 2 - 180 degrees
      # 3 - 270 degrees
      # 4 - flipped
      # 5 - flipped + 90 degrees
      # 6 - flipped + 180 degrees
      # 7 - flipped + 270 degrees
#   mirror = <NAME>
#   bitdepth = (10)
#   cm =
      # auto    - srgb for 8bpc, wide for 10bpc if supported (recommended)
      # srgb    - sRGB primaries (default)
      # dcip3   - DCI P3 primaries
      # dp3     - Apple P3 primaries
      # adobe   - Adobe RGB primaries
      # wide    - wide color gamut, BT2020 primaries
      # edid    - primaries from edid (known to be inaccurate)
      # hdr     - wide color gamut and HDR PQ transfer function (experimental)
      # hdredid - same as hdr with edid primaries (experimental)
#   sdrbrightness = number
#   sdrsaturation = number
#   vrr =
      # 0 - off
      # 1 - on
      # 2 - fullscreen only
      # 3 - fullscreen with video or game content type
#   disabled = (false, true)
# }

monitor = , preferred, auto, auto

monitorv2 {
  output = eDP-1
  # output = desc:California Institute of Technology 0x1509
  mode = 2560x1440@60
  position = 0x0
  scale = 1.60
  vrr = 1
}

monitorv2 {
  output = desc:Xiaomi Corporation P24FBA-RAGL 5438700015282
  mode = 1920x1080@60
  position = -160x-1080
  scale = 1
  transform = 2
}

monitorv2 {
  output = desc:Invalid Vendor Codename - RTK C-1 demoset-1
  mode = 1920x1080@60
  # position = 1600x0 # right
  position = -1600x0 # left
  scale = 1.20
}

# Lid management
# https://wiki.hypr.land/Configuring/Binds/#switches
# https://github.com/hyprwm/Hyprland/discussions/11093

bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1", disable
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor $eDP_1
