return {
  --  { "akinsho/bufferline.nvim",
  --    event = "VeryLazy",
  --    dependencies = { "nvim-mini/mini.icons" },
  --    keys = {
  --      { "<Tab>",      "<Cmd>BufferLineCycleNext<Cr>",   desc = "Next buffer" },
  --      { "<S-Tab>",    "<Cmd>BufferLineCyclePrev<Cr>",   desc = "Prev buffer" },
  --      { "<leader>bp", "<Cmd>BufferLineTogglePin<Cr>",   desc = "Toggle Pin" },
  --      { "<leader>bo", "<Cmd>BufferLineCloseOthers<Cr>", desc = "Delete Other Buffers" },
  --    },
  --    ---@module "bufferline"
  --    ---@type bufferline.UserConfig
  --    opts = {
  --      options = {
  --        separator = "slant",
  --        always_show_bufferline = true,
  --
  --        show_buffer_icons = true,
  --        show_buffer_close_icons = true,
  --
  --        diagnostics = "nvim_lsp",
  --
  --        hover = {
  --          enabled = true,
  --          delay = 200,
  --          reveal = { "close" },
  --        },
  --
  --        -- fylerバッファをbufferlineから除外
  --        custom_filter = function(buf_number, buf_numbers)
  --          local buftype = vim.bo[buf_number].buftype
  --          local filetype = vim.bo[buf_number].filetype
  --
  --          -- fylerバッファを除外
  --          if filetype == "fyler" then
  --            return false
  --          end
  --
  --          -- その他の特殊バッファも除外（オプション）
  --          if buftype == "quickfix" or buftype == "terminal" then
  --            return false
  --          end
  --
  --          return true
  --        end,
  --      },
  --    },
  --  },
}
